#!/usr/bin/env python3

import rclpy
from rclpy.executors import MultiThreadedExecutor

from ros_engine_sound_sim.ros_engine_sound_sim import RosEngineSoundSim

if __name__ == "__main__":
    rclpy.init(args=None)
    executor = MultiThreadedExecutor()

    sound = RosEngineSoundSim()
    sound.configure()

    rclpy.spin(sound, executor=executor)

    sound.destroy_node()
    rclpy.shutdown()